### ISSUE TITLE
having trouble with the api

### ISSUE THREAD

**Issue by 0xzoo** [BagelNetwork/Client#53]
getting the error `AttributeError("'list' object has no attribute 'user_id'")` when querying "/api/v1/clusters/{cluster_id}/count". am I missing something? any help would be appreciated.

**Comment by Rijul1204** [comment]
Thank you, @0xzoo, for reporting the issue. Can you please check again now? There was an intermittent issue with one of our servers, but it has been resolved. You should now be able to query the cluster to get the count.

Please let me know if you encounter any other issues. We highly appreciate feedback from the community.

**Comment by 0xzoo** [comment]
ty! yes its fixed now

**Comment by 0xzoo** [comment]
what's the format for putting our api key in headers?

**Comment by Rijul1204** [comment]
You need to use the header field name x-api-key to provide the API key value. It's not required for public clusters but is necessary for private clusters.

Here's a sample curl command format:

```
curl -X 'GET' \
  'https://api.bageldb.ai/api/v1/clusters/{cluster_id}/count' \
  -H 'accept: application/json' \
  -H 'x-api-key: xyz'
```

**Comment by 0xzoo** [comment]
am having trouble adding via the api. works fine on docs (https://api.bageldb.ai/docs#/default/add) but when I POST via the api i get the error:
```
{
  detail: [
    {
      type: 'model_attributes_type',
      loc: ['body'],
      msg: 'Input should be a valid dictionary or object to extract fields from',
      input: '{"embeddings":null,"metadatas":null,"documents":["how does it make you feel?"],"uris":null,"ids":["2"]}',
      url: 'https://errors.pydantic.dev/2.6/v/model_attributes_type'
    }
  ]
}
```

**Comment by Rijul1204** [comment]
How are you making the API calls? Is it through Postman or directly in your code? Could you please share that with me? If it's working via the doc site, that indicates the server is functioning properly. We need to examine how the POST method is being used. I can take a look into the code to help diagnose the issue further. 
Also, If you want to use a simpler method for interacting with BagelDB, you can try our BagelDB console or Python client.

Here is a sample payload you might use. I've tested it via Postman:
```

{
    "ids": [
        "id_doc"
    ],
    "documents": [
        "testing doc creation"
    ]
}

```

**Comment by 0xzoo** [comment]
my function is below. making it directly in my code in typescript. edited to match the simpler payload, but getting the same error with the updated input
```
export async function addEntry(qEntry: QEntry) {
  const {
    // embeddings,
    // metadatas, 
    documents,
    // uris
  } = qEntry
  const id = (await getCount() + 1).toString()
  const fullEntry: QEntry = {
    documents: documents || null,
    ids: [id]
  }
  const response = await fetch(`${baseAPIURL}/clusters/${process.env.BAGELDB_CLUSTER_ID}/add`, {
    method: 'POST',
    headers: {
      'accept': 'application/json',
      'x-api-key': process.env.BAGELDB_API_KEY as string
    },
    body: JSON.stringify(fullEntry)
  })
  const data = await response.json()
  if (!data) {
    throw new Error("Empty response data received")
  }
  console.log(data)
  return data
}
```

**Comment by Rijul1204** [comment]
Most likely, the issue is with how the request is formatted. Please include `'Content-Type': 'application/json'` in your request headers to inform the server that the body of the request is in JSON format.

Updated code: 

```
const response = await fetch(`${baseAPIURL}/clusters/${process.env.BAGELDB_CLUSTER_ID}/add`, {
  method: 'POST',
  headers: {
    'Accept': 'application/json',
    'Content-Type': 'application/json', // Explicitly declare the content type as JSON
    'X-API-Key': process.env.BAGELDB_API_KEY // Not mandatory if you're using a public cluster.
  },
  body: JSON.stringify(fullEntry)
});
```

Please let us know if the issue persists. Also, just to inform you we're working on releasing our JavaScript client soon to simplify the calling process.

**Comment by 0xzoo** [comment]
that worked 😅 thank you v much
